Repository owncloud/contacts, pull requests merged in 2018-12, with the labels that each got.

#650 Release 1.5.5
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3 - to review

#645 Add setup for running tests in drone CI
  .drone.yml
  .gitignore
  .phan/config.php
  .php_cs.dist
  .travis.yml
  Makefile
  composer.json
  composer.lock
  js/tests/run-js-test.sh
  karma.conf.js
  package.json
  phpstan.neon
  phpunit.integration.xml
  phpunit.xml
  tests/bootstrap.php
  vendor-bin/owncloud-codestyle/composer.json
  vendor-bin/phan/composer.json
  vendor-bin/phpstan/composer.json
Labels: 3 - to review, Drone, QA-team

#651 Remove travis
  .travis.yml
Labels: 3 - to review, QA-team

#652 Apply code style
  .drone.yml
  appinfo/routes.php
  js/dav/test/integration/server/calendarserver.php
  tests/integration/AppTest.php
  tests/unit/controller/PageControllerTest.php
Labels: 3 - to review, QA-team

#653 Do not pin coding-standard to PHP 5.6
  vendor-bin/owncloud-codestyle/composer.json
Labels: 4 - to release, QA-team
