Repository owncloud/contacts, pull requests merged in 2020-06, with the labels that each got.

#691 Updating bamarni/composer-bin-plugin (1.4.0 => 1.4.1)
  composer.lock
Labels: 3 - to review, dependencies

#692 Put new bootstrapFiles section in phpstan.neon
  phpstan.neon
Labels: 3 - to review, QA-team

#694 Use selenium version 3.141.59-20200525
  .drone.star
Labels: QA-team
